<?xml version="1.0"?>

<st-source>
<time-stamp>From VisualWorks® Personal Use Edition, 8.2 of 15 July 2016 on 12 September 2017 at 11:10:51 PM</time-stamp>


<component-created>
<name>Faish-Tests</name> <type>package</type>
</component-created><!-- Package Faish-Tests* -->


<component-created>
<name>Faish-Tests</name> <type>package</type>
</component-created>

<class>
<name>TestCache</name>
<environment>Smalltalk</environment>
<super>Core.Object</super>
<private>false</private>
<indexed-type>none</indexed-type>
<inst-vars></inst-vars>
<class-inst-vars></class-inst-vars>
<imports></imports>
<category></category>
<attributes>
<package>Faish-Tests</package>
</attributes>
</class>

<comment>
<class-id>TestCache</class-id>
<body>Disable this test for now. I don't have caches (memoization).</body>
</comment>


</st-source>
